# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    ignore:
      # Must wait until cspell version 7 to go ES Modules
      - dependency-name: "get-stdin" # Needs ES Modules
        versions: [">=9"]
      - dependency-name: "configstore" # Needs ES Modules
        versions: [">=6"]
      - dependency-name: "strip-ansi" # Needs ES Modules
        versions: [">=7"]

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    # The Gemfile used in for the Jekyll doc site
    directory: "/docs"
    schedule:
      interval: "weekly"

  # - package-ecosystem: "npm" # See documentation for possible values
  #   directory: "/" # Location of package manifests
  #   versioning-strategy: increase
  #   target-branch: "cspell5"
  #   schedule:
  #     interval: "weekly"
  #   ignore:
  #     - dependency-name: "configstore"
  #       versions: [">=6"]
  #     - dependency-name: "get-stdin"
  #       versions: [">=9"]
  #     - dependency-name: "commander"
  #       versions: [">=8"]

  # - package-ecosystem: "github-actions"
  #   # Workflow files stored in the
  #   # default location of `.github/workflows`
  #   directory: "/"
  #   target-branch: "cspell5"
  #   schedule:
  #     interval: "daily"
