# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
      nodeVersion: '12.x'
    linux10:
      imageName: 'ubuntu-16.04'
      nodeVersion: '10.x'
    linux13:
      imageName: 'ubuntu-16.04'
      nodeVersion: '13.x'
    mac:
      imageName: 'macos-latest'
      nodeVersion: '12.x'
    windows:
      imageName: 'windows-latest'
      nodeVersion: '12.x'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(nodeVersion)
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- script: |
    npm test
  displayName: 'unit tests'

- script: |
    npm run test-spec
  displayName: 'spec tests'

- bash: |
    node ./bin.js trace test
    node ./bin.js "**/{*.ts,*.md}"
  displayName: 'Validation: run cspell'
