ignorePaths:
  - '*.{ts,js}'
  - 'cspell*.{json,yaml}'
ignoreWords:
  - quic
  - tsbuildinfo
words:
  - pnpm
flagWords:
  - blacklist->denylist
  - whitelist->allowlist
  - cafÃ©->cafe
  - bluelist->greenList
  - Bluelist->GreenList
