dictionaryDefinitions:
  - name: workspace
    path: ../cspell-dict.txt
    description: Custom Workspace Dictionary
    addWords: true
    scope: workspace
ignorePaths:
  - "*.svg"
  - /build
  - cspell.*
  - auto_*.md
languageSettings:
  - languageId: typescript,typescriptreact,json,css,yaml
    words:
      - clsx
      - typecheck
      - browserslist
      - padding-horiz
      - Infima
enableFiletypes:
  - mdx
words:
  - callouts
  - jamstack
