name: cSpell-cli
on:
  pull_request:
  push:
    branches:
      - main
  # Run on demand
  workflow_dispatch:

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
        with:
          cache: npm

      - run: npm i -g npm@8
      - run: npm -v

      - name: cache node_modules
        uses: actions/cache@v2
        with:
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          path: |
            **/node_modules

      - run: npm i

      - name: prepare-cspell-action Cache
        id: prepare-cspell-action-cache
        uses: actions/cache@v2
        with:
          key: prepare-cspell-action-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn2/**/package.json') }}
          path: |
            **/yarn2/**/pnp.*
            **/yarn2/**/.yarn

      - name: prepare-cspell-action
        # if: steps.prepare-cspell-action-cache.outputs.cache-hit != 'true'
        run: npm run prepare-cspell-action

      - name: Restore CSpell cache
        uses: actions/cache@v2
        with:
          key: cspell-${{ runner.os }}
          path: |
            .cspellcache

      - name: cspell@latest
        run: npx cspell@latest --cache --cache-strategy content --cache-location .cspellcache  "**"
