# https://github.com/dependabot/dependabot-core/issues/1736
name: Dependabot - Process Recreate Pull Requests
on:
  # Trigger this workflow most changes. We want it to check if something needs to be done when a change happens.
  pull_request:
    types:
      - closed
      - reopened
      - opened
      - synchronize
      - labeled
      - unlabeled
  workflow_dispatch:
  push:
permissions: read-all
jobs:
  add-comment-recreate:
    runs-on: ubuntu-latest
    # permissions:
    #   pull-requests: write
    #   contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Show Event Data
        env:
          PR_DATA: ${{ toJSON(github.event) }}
        run: |
          echo "$PR_DATA"

      - name: Remove Labels
        if: ${{ contains(github.event.pull_request.labels.*.name, 'dependabot:recreate-in-progress') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit --remove-label "dependabot:recreate-in-progress" --remove-label "dependabot:recreate" ${{ github.event.pull_request.number }}

      - name: Show Open PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr list -S "author:app/dependabot"

      - name: Has PRs in progress?
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo PR_IN_PROGRESS=$(
            gh pr list -S "label:dependabot:recreate-in-progress author:app/dependabot" --json number | jq -r '.[0].number || ""'
          ) >> $GITHUB_ENV

      - name: Get List of PRs to Update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo PR_SUMMARY=$(gh pr list -S "label:dependabot:recreate author:app/dependabot") >> $GITHUB_ENV

      - name: Calc PR to Recreate
        if: ${{ !env.PR_IN_PROGRESS && env.PR_SUMMARY }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo PR_TO_RECREATE=$(
            gh pr list -S "label:dependabot:recreate author:app/dependabot" --json number | jq -r 'if .[0] then .[0].number else "" end'
          ) >> $GITHUB_ENV

      - name: Display
        run: |
          echo $PR_IN_PROGRESS

      - name: Tell Dependabot to Recreate PR
        if: ${{ env.PR_TO_RECREATE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit --add-label "dependabot:recreate-in-progress" $PR_TO_RECREATE
          gh pr comment -b "@dependabot recreate" $PR_TO_RECREATE

      # - name: Get Open PRs and apply comment
      #   if: ${{ env.PR_SUMMARY }}
      #   env:
      #     GH_TOKEN: ${{ secrets.TOKEN_UPDATE_DEPENDABOT }}
      #   run: >
      #     gh pr list -S "-label:cspell5 author:app/dependabot" --json number
      #     | jq '.[].number'
      #     | xargs -n1 gh pr comment -b "@dependabot recreate"
