name: R - Create PR from Artifact

on:
  workflow_call:
    inputs:
      patch_artifact:
        description: Name of the Artifact
        required: true
        type: string
      patch_path:
        description: Patch diff files
        required: false
        type: string
        default: '*.diff'
      base:
        description: The Base Ref to apply the diff
        required: true
        type: string
      body:
        description: Optional body of the PR
        required: false
        type: string
      commit-message:
        description: Commit Message for the PR
        required: true
        type: string
      branch:
        description: The Branch to create for the PR
        required: true
        type: string
      title:
        description: PR title - defaults to commit-message
        required: false
        type: string
    secrets:
      app_id:
        required: true
      private_key:
        required: true

permissions:
  contents: read

jobs:
  pr:
    runs-on: ubuntu-latest

    env:
      REF_BRANCH: ${{ inputs.base }}

    steps:
      # - name: Input
      #   env:
      #     INPUT: ${{ toJSON(inputs) }}
      #   run: |
      #     echo "$INPUT"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ env.REF_BRANCH }}

      - name: Restore Artifact
        uses: actions/download-artifact@v6
        with:
          name: ${{ inputs.patch_artifact }}
          path: temp

      - name: show downloaded
        run: ls -alFR temp
      # - name: show diff
      #   run: cat temp/*.diff

      - name: apply diff
        run: |
          git apply --allow-empty temp/${{ inputs.patch_path }}

      - name: PR Body
        id: body
        uses: streetsidesoftware/actions/public/pr-body@v1
        with:
          title: ${{ inputs.title }}
          message: |
            ${{ inputs.commit-message }}

      - name: Create Pull Request
        uses: streetsidesoftware/actions/.github/actions/pr@v1
        with:
          commit-message: ${{ inputs.commit-message }}
          branch: ${{ inputs.branch }}
          base: ${{ inputs.base }}
          title: ${{ inputs.title || inputs.commit-message }}
          body: ${{ steps.body.outputs.body }}
          app_id: ${{ secrets.app_id }}
          app_private_key: ${{ secrets.private_key }}
