name: Version

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run on "master" or "cspell4"'
        default: master
        required: true

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Install
        run: npm install
      #       - name: Test
      #         run: npm test
      - name: Setup Git
        run: |
          git config --local user.name 'Jason Dent'
          git config --local user.email 'jason@streetsidesoftware.nl'
      - name: Version Master
        if: ${{ github.event.inputs.branch == 'master' }}
        run: npm run pub-version-pre -- -y
      - name: Version cspell4
        if: ${{ github.event.inputs.branch == 'cspell4' }}
        run: npm run pub-version -- -y
