name: Version

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run on "main" or "cspell4"'
        default: main
        required: true

permissions:
  contents: read

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Install
        run: npm install
      #       - name: Test
      #         run: npm test
      - name: Setup Git
        run: |
          git config --local user.name 'Jason Dent'
          git config --local user.email 'jason@streetsidesoftware.nl'
      - name: Version Main
        if: ${{ github.event.inputs.branch == 'main' }}
        run: npm run pub-version-pre -- -y
      - name: Version cspell4
        if: ${{ github.event.inputs.branch == 'cspell4' }}
        run: npm run pub-version -- -y
