name: Workflow Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1" # Monday at 8 UTC

permissions:
  contents: read

env:
  NEW_BRANCH: "update-integration-repositories"
  REF_BRANCH: main
  RUNS_ON: ubuntu-latest
  NODE_VERSION: "16.x"
  NPM_VERSION: "8"

jobs:
  load-integrations:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.read-integrations.outputs.repos }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REF_BRANCH }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            packages/*/package-lock.json
            integration-tests/package-lock.json

      - run: npm i -g npm@${{ env.NPM_VERSION }}
      - run: npm -v
      - id: read-integrations
        run: |
          echo "::set-output name=repos::$(tr \"\\n\" " " < .github/integrations.json)"

  integrations-x:
    runs-on: ubuntu-latest
    needs:
      - load-integrations
    env:
      LOAD_INTEGRATIONS: ${{ needs.load-integrations.outputs.repos }}
      OUTPUTS: ${{ toJSON(needs.load-integrations.outputs) }}
    steps:
      - run: |
          echo $LOAD_INTEGRATIONS
          echo $OUTPUTS

  integrations:
    runs-on: ubuntu-latest
    needs:
      - load-integrations
    outputs:
      repo: ${{ matrix.repo }}

    strategy:
      # the integration tests are independent, so we want to run them all.
      fail-fast: false
      matrix:
        # List of repositories to check.
        # Use `repo-list.sh` in `integration-tests` to generate.
        # repo: ${{ fromJSON(needs.load-integrations.outputs.repos) }}
        repo:
          - googleapis/google-cloud-cpp

    steps:
      - name: Repo Info
        id: step-repo-info
        run: |
          mkdir temp
          echo "${{ matrix.repo }}"
          echo "${{ matrix.repo }}" > temp/repo-name.txt
          echo "::set-output name=repo::${{ matrix.repo }}" | sed "s/[/]/__/g"
      - name: store diff
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.step-repo-info.outputs.repo }}
          path: temp/repo-name.txt

  pr:
    runs-on: ubuntu-latest
    needs: integrations

    env:
      OUTPUT: ${{ toJSON(needs.integrations.outputs) }}

    steps:
      - name: echo
        run: |
          echo "$OUTPUT"
      - name: restore repos
        uses: actions/download-artifact@v3
        with:
          path: temp
      - name: show downloaded
        run: cat temp/*/repo-name.txt
# cspell:ignore apollographql
# cspell:ignore aspnetboilerplate
# cspell:ignore caddyserver
# cspell:ignore logiciel twbs
# cspell:ignore MartinThoma googleapis
# cspell:ignore plasticrake tplink smarthome
